//Database for the fishList module

export const database = {
  fish: [
    {
      name: "Nemo",
      species: "Clownfish",
      length: 3,
      location: "Great Barrier Reef",
      diet: "Omnivore",
      image: "styles/images/clownfish.jpeg",
    },
    {
      name: "Dory",
      species: "Blue Tang",
      length: 10,
      location: "Great Barrier Reef",
      diet: "Omnivore",
      image: "styles/images/bluetang.jpeg",
    },
    {
      name: "Gill",
      species: "Moorish Idol",
      length: 7,
      location: "Great Barrier Reef",
      diet: "Omnivore",
      image: "styles/images/moorish-idol.jpeg",
    },
    {
      name: "Bloat",
      species: "Porcupine Pufferfish",
      length: 5,
      location: "Great Barrier Reef",
      diet: "Carnivore",
      image: "styles/images/porcupine-pufferfish.jpeg",
    },
    {
      name: "Bubbles",
      species: "Yellow Tang",
      length: 8,
      location: "Great Barrier Reef",
      diet: "Herbivore",
      image: "styles/images/yellow-tang.jpeg",
    },
    {
      name: "Gurgle",
      species: "Royal Gramma",
      length: 4,
      location: "Great Barrier Reef",
      diet: "Carnivore",
      image: "styles/images/royal-gramma.jpeg",
    },

    {
      name: "Marly",
      species: "Marlin",
      length: 3,
      location: "Great Barrier Reef",
      diet: "Omnivore",
      image: "styles/images/Marlin.jpeg",
    },
    {
      name: "Bruce",
      species: "Great White Shark",
      length: 240,
      location: "Open Ocean",
      diet: "Carnivore",
      image: "styles/images/Shark.jpeg",
    },
    {
      name: "Star",
      species: "Starfish",
      length: 6,
      location: "Indo-Pacific Reefs",
      diet: "Omnivore",
      image: "styles/images/starfish.jpeg",
    },
    {
      name: "Bill",
      species: "Hammerhead Shark",
      length: 10,
      location: "Hawaiian Islands",
      diet: "Herbivore",
      image: "styles/images/Hammerhead.jpeg",
    },
    {
      name: "Peach",
      species: "Pink Sea Star",
      length: 15,
      location: "Coral Reefs",
      diet: "Carnivore",
      image: "styles/images/PinkSeasSar.jpeg",
    },
    {
      name: "Bloat",
      species: "Pufferfish",
      length: 12,
      location: "Tropical Waters",
      diet: "Omnivore",
      image: "styles/images/pufferfish.jpeg",
    },
    {
      name: "Fred",
      species: "Octopus",
      length: 3,
      location: "Caribbean Sea",
      diet: "Carnivore",
      image: "styles/images/octopus.jpeg",
    },
    {
      name: "Jacques",
      species: "Pacific Cleaner Shrimp",
      length: 5,
      location: "Coral Reefs",
      diet: "Carnivore",
      image: "styles/images/shrimp.jpeg",
    },
    {
      name: "Deb",
      species: "Four-Stripe Damselfish",
      length: 9,
      location: "Western Pacific",
      diet: "Omnivore",
      image: "styles/images/damselfish.jpeg",
    },
    {
      name: "Crush",
      species: "Green Sea Turtle",
      length: 45,
      location: "East Australian Current",
      diet: "Herbivore",
      image: "styles/images/seaturtle.jpeg",
    },
  ],
};
